"""Dreaming to Dodge — PLAYABLE neural simulator (Modal web app).

There is NO game engine here: the VizDoom world model (VQ-VAE tokenizer + GPT)
predicts each next first-person frame in response to your keypresses. You can
play it yourself (arrow keys) or watch the imagination-trained agent play. Served
as a public Modal web endpoint.

Deploy:  .venv/bin/modal deploy modal_apps/simulator.py   (-> public *.modal.run URL)
"""
import modal
from common import IMAGE, VOLUMES, VOL, VOL_PATH, ckpt_path, data_path

app = modal.App("dreaming-to-dodge-sim")
SIM_IMAGE = IMAGE.pip_install("fastapi[standard]==0.115.6")

FRONTEND = r"""<!doctype html><html><head><meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1">
<title>Dreaming to Dodge — play inside a world model</title>
<style>
  :root{--bg:#ffffff;--fg:#161a20;--mut:#5c626f;--acc:#0f8f68;--warn:#b23636;--line:#e8eaef;--soft:#f6f7f9}
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--fg);font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
       display:flex;flex-direction:column;align-items:center;min-height:100vh;padding:24px}
  h1{font-weight:700;font-size:22px;margin:4px 0 2px;letter-spacing:-.02em}
  .sub{color:var(--mut);font-size:14px;margin:0 0 18px;text-align:center;max-width:640px;line-height:1.5}
  #stage{position:relative;width:512px;max-width:92vw;aspect-ratio:1/1;background:#0d0f14;border-radius:12px;overflow:hidden;
         box-shadow:0 14px 40px -18px rgba(30,41,59,.45);border:1px solid var(--line);image-rendering:pixelated}
  #screen{width:100%;height:100%;image-rendering:pixelated;display:block}
  #hud{position:absolute;top:10px;left:12px;font-variant-numeric:tabular-nums;font-size:15px;color:#fff;
       text-shadow:0 1px 3px #000;pointer-events:none}
  #hud b{color:#5fe0b0}
  #over{position:absolute;inset:0;display:none;align-items:center;justify-content:center;flex-direction:column;
        background:rgba(13,15,20,.62);color:#fff;font-size:20px;gap:10px}
  .row{display:flex;gap:10px;margin-top:16px;flex-wrap:wrap;justify-content:center;align-items:center}
  button{background:#fff;color:var(--fg);border:1px solid var(--line);border-radius:9px;padding:9px 16px;
         font-size:14px;cursor:pointer;box-shadow:0 1px 2px rgba(30,41,59,.06)}
  button:hover{border-color:var(--acc)}
  button.on{background:var(--acc);color:#fff;border-color:var(--acc);font-weight:600}
  #over button{background:#fff;color:var(--fg)}
  .hint{color:var(--mut);font-size:13px;margin-top:14px;text-align:center}
  kbd{background:var(--soft);border:1px solid var(--line);border-radius:5px;padding:1px 7px;font-size:12px}
  #fps{color:var(--mut);font-size:12px}
</style></head><body>
<h1>Dreaming to Dodge</h1>
<p class=sub>You are inside a neural network. There is no game engine — a Transformer
<b>world model</b> predicts each next frame from your action. The monsters and their fireballs
aren't scripted or random — they're part of the game dynamics the model <b>learned to predict</b>.
Strafe to dodge them.</p>
<div id=stage>
  <canvas id=screen width=64 height=64></canvas>
  <div id=hud>steps <b id=steps>0</b> &nbsp; tics <b id=tics>0</b></div>
  <div id=over><div id=overmsg>you were hit</div><button onclick="reset()">dream again</button></div>
</div>
<div class=row>
  <button id=bplay class=on onclick="setMode('human')">🎮 you play</button>
  <button id=bai onclick="setMode('agent')">🤖 watch the AI</button>
  <button onclick="reset()">↻ reset</button>
  <span id=fps></span>
</div>
<p class=hint>Hold <kbd>←</kbd> / <kbd>→</kbd> to strafe. The frames you see are generated by the world model, not a renderer.</p>
<script>
const cv=document.getElementById('screen'),ctx=cv.getContext('2d');
let sid=null,mode='human',held=0,alive=true,steps=0,busy=false,tPrev=performance.now(),ema=0;
const img=ctx.createImageData(64,64);
function draw(b64){const im=new Image();im.onload=()=>{ctx.drawImage(im,0,0,64,64)};im.src='data:image/png;base64,'+b64;}
async function reset(){const r=await fetch('reset',{method:'POST'});const j=await r.json();sid=j.session;steps=0;alive=true;
  document.getElementById('steps').textContent=0;document.getElementById('tics').textContent=0;
  document.getElementById('over').style.display='none';draw(j.frame);}
function setMode(m){mode=m;document.getElementById('bplay').className=m==='human'?'on':'';
  document.getElementById('bai').className=m==='agent'?'on':'';}
async function tick(){
  if(!sid||!alive||busy){return;}
  busy=true;
  const a = mode==='agent' ? -1 : held;            // -1 => let the trained controller act
  try{
    const r=await fetch('step',{method:'POST',headers:{'Content-Type':'application/json'},
      body:JSON.stringify({session:sid,action:a,agent:mode==='agent'})});
    const j=await r.json();draw(j.frame);steps=j.steps;
    document.getElementById('steps').textContent=j.steps;
    document.getElementById('tics').textContent=j.steps*4;
    const now=performance.now();ema=0.9*ema+0.1*(1000/(now-tPrev));tPrev=now;
    document.getElementById('fps').textContent=ema.toFixed(1)+' fps';
    if(j.done){alive=false;document.getElementById('overmsg').textContent=
      (mode==='agent'?'the AI survived ':'you survived ')+j.steps+' steps ('+(j.steps*4)+' tics)';
      document.getElementById('over').style.display='flex';}
  }catch(e){}
  busy=false;
}
document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')held=1;else if(e.key==='ArrowRight')held=2;});
document.addEventListener('keyup',e=>{if((e.key==='ArrowLeft'&&held===1)||(e.key==='ArrowRight'&&held===2))held=0;});
setInterval(tick,110);   // ~9 fps target; server GPU step is the bottleneck
reset();
</script></body></html>"""


@app.function(image=SIM_IMAGE, gpu="A10G", volumes=VOLUMES, timeout=60 * 60,
                  max_containers=1)
@modal.concurrent(max_inputs=8)
@modal.asgi_app()
def web():
    import io, base64, uuid, numpy as np, torch
    from fastapi import FastAPI, Request
    from fastapi.responses import HTMLResponse, JSONResponse
    from PIL import Image
    from tokenizer import Tokenizer, TokenizerConfig
    from world_model import WorldModel, WorldModelConfig
    from controller import Reducer, TinyController
    from common import load_buffer

    device = "cuda" if torch.cuda.is_available() else "cpu"
    TAG = "doom"
    K, VOCAB, EMB, CH = 64, 512, 128, 64
    L, WEMB, WLAY, WHEADS = 16, 256, 8, 4
    A = 3
    VOL.reload()
    tok = Tokenizer(TokenizerConfig(resolution=64, ch=CH, num_tokens=K, vocab_size=VOCAB,
                                    embed_dim=EMB)).to(device).eval()
    tok.load_state_dict(torch.load(ckpt_path(TAG, "tokenizer"), map_location=device))
    wm = WorldModel(WorldModelConfig(num_tokens=K, vocab_size=VOCAB, num_actions=A, max_timesteps=L,
                                     embed_dim=WEMB, num_layers=WLAY, num_heads=WHEADS)).to(device).eval()
    wm.load_state_dict(torch.load(ckpt_path(TAG, "world_model"), map_location=device))
    cdata = torch.load(ckpt_path(TAG, "controllerc6"), map_location=device)
    reducer = Reducer(rows=cdata.get("rows", 3), cols=cdata.get("cols", 6), device=device)
    ctrl = TinyController(reducer.fdim, A, hidden=cdata.get("hidden", 16))
    thetas = ([t.to(device) for t in cdata["thetas"]] if cdata.get("use_ensemble") and cdata.get("thetas")
              else [cdata["theta"].to(device)])

    # a pool of real START frames to begin the dream from
    frames, _, _, _ = load_buffer(data_path(TAG))
    start_pool = torch.tensor(frames[np.random.RandomState(0).choice(len(frames), 64, replace=False)]).permute(0, 3, 1, 2)

    sessions = {}

    def png_b64(t):
        arr = (t.clamp(0, 1).cpu().numpy().transpose(1, 2, 0) * 255).astype(np.uint8)
        im = Image.fromarray(arr).resize((256, 256), Image.NEAREST)
        buf = io.BytesIO(); im.save(buf, format="PNG")
        return base64.b64encode(buf.getvalue()).decode()

    api = FastAPI()

    @api.get("/")
    def index():
        return HTMLResponse(FRONTEND)

    @api.post("/reset")
    def reset():
        sid = uuid.uuid4().hex[:12]
        i = int(np.random.randint(len(start_pool)))
        x0 = start_pool[i:i + 1].to(device)
        with torch.no_grad():
            th = tok.encode(x0).unsqueeze(1)                       # (1,1,K)
            frame = tok.decode(th[:, -1])[0]
            feat = reducer.features(tok.decode(th[:, -1]))
        sessions[sid] = {"tokens": th, "actions": torch.zeros(1, 1, dtype=torch.long, device=device),
                         "feat_prev": feat, "steps": 0, "alive": True}
        return JSONResponse({"session": sid, "frame": png_b64(frame)})

    @api.post("/step")
    async def step(req: Request):
        body = await req.json()
        sid = body.get("session"); s = sessions.get(sid)
        if s is None or not s["alive"]:
            return JSONResponse({"done": True, "steps": s["steps"] if s else 0, "frame": ""})
        with torch.no_grad():
            if body.get("agent"):
                cur = tok.decode(s["tokens"][:, -1]); fc = reducer.features(cur)
                feats = torch.cat([fc, s["feat_prev"]], -1)
                a = int(sum(ctrl.logits_single(feats, t) for t in thetas).argmax(-1).item())
                s["feat_prev"] = fc
            else:
                a = int(body.get("action", 0)); a = a if a in (0, 1, 2) else 0
            s["actions"][:, -1] = a
            nxt, _, done = wm.generate_step_fast(s["tokens"], s["actions"], temperature=1.0, sample=True)
            s["tokens"] = torch.cat([s["tokens"], nxt.unsqueeze(1)], 1)[:, -L:]
            s["actions"] = torch.cat([s["actions"], torch.zeros(1, 1, dtype=torch.long, device=device)], 1)[:, -L:]
            frame = tok.decode(s["tokens"][:, -1])[0]
            s["feat_prev"] = s.get("feat_prev") if body.get("agent") else reducer.features(tok.decode(s["tokens"][:, -1]))
            s["steps"] += 1
            dead = bool(int(done.item()))
            if dead or s["steps"] >= 525:
                s["alive"] = False
        return JSONResponse({"frame": png_b64(frame), "done": (not s["alive"]), "steps": s["steps"]})

    return api
